name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: ' Features'
    labels: ['feature', 'enhancement']
  - title: ' Fixes'
    labels: ['bug', 'fix']
change-template: '- $TITLE (#$NUMBER)'
no-changes-template: 'No significant changes'
template: |
  ## Changes
  $CHANGES
