name: Code Review Automation

on:
  pull_request:
    branches: [ main ]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (if available)
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script found, skipping."
          fi

      - name: Run security audit
        run: |
          echo "Scanning for vulnerabilities..."
          npm audit --audit-level=moderate || true

      - name: Check code formatting
        run: |
          if npm run | grep -q "format"; then
            npm run format --check || true
          else
            echo "No format script found, skipping."
          fi

      - name: Comment PR summary
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ✅ **Automated Code Review Results**
            - Lint & formatting checked
            - Security audit performed
            - Please review warnings in the Actions logs if any
